# My First Workflow to create with editor
name: First Workflow

on:
  push:
    branches: 
      - main
      - develop
  workflow_dispatch:

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest

    steps:
      - name: Greet the Author
        run: |
          echo " Hello ${{ vars.WHO_TO_GREET }}👋 from ${{ github.actor}}"
          echo " You are currently in '${{ github.ref}}'"
          echo " My Secret is ${{ secrets.MY_SECRET }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Display file structure
        run: tree

  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job

    steps:
      - run: |
         echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
         sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
         echo "My secret is  '$sec'."


  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: Test

    steps:
      - run: |
         echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
         sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
         echo "My secret is  '$sec'."

  production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: [ Test, Load-Test]

    steps:
      - run: |
         echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
         sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
         echo "My secret is  '$sec'."

    
    
