# My First Workflow to create with editor
name: First Workflow

on:
  push:
    branches: 
      - main
      - develop
  workflow_dispatch:

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest

    steps:
      - name: Greet the Author
        run: |
          echo " Hello ${{ vars.WHO_TO_GREET }}👋 from ${{ github.actor}}"
          echo " You are currently in '${{ github.ref}}'"
          echo " My Secret is ${{ secrets.MY_SECRET }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Display file structure
        run: tree
    
